name: IdenfierFlow
description: Reconhecimento facial.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  http: ^0.13.6
  path_provider: ^2.0.0  # Para salvar imagens temporariamente
  camera: ^0.10.0  # Substitua pela última versão
  image: ^4.5.2     # Atualizado para resolver o conflito com flutter_launcher_icons
  udp: ^5.0.3
  supabase_flutter: ^2.8.3
  bcrypt: ^1.1.3
  google_mlkit_face_detection: ^0.12.0
  image_picker: ^1.1.2
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/icons/IdentifierFlow_logo.png"

flutter:
  uses-material-design: true

  assets:
    - lib/icons/
